added filter for user
JupiterOne/graph-zendesk pull request #33
Opened 2024-07-18 16:32 UTC by poornima-metron

2024-07-23 17:09 UTC, suraj-metron requested changes

2024-07-23 17:09 UTC, suraj-metron commented on src/steps/account/__recordings__/fetchAccount_3692983622/recording.har
> +              "value": "metronsecurity.zendesk.com"
I see metronsecurity at lots of places, why is it so?

2024-07-24 06:14 UTC, poornima-metron commented on src/steps/account/__recordings__/fetchAccount_3692983622/recording.har
> +              "value": "metronsecurity.zendesk.com"
we used actual subdomain to record new recordings as the `creativice` subdomain gave errors

2024-08-08 15:58 UTC, Gonzalo-Avalos-Ribas approved these changes

2024-08-08 18:57 UTC, merged